name: Auto close 
on: [pull_request]  
jobs:  
  close:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/github-script@v6  
        with:  
          script: |  
            github.rest.pulls.update({  
              owner: context.repo.owner,  
              repo: context.repo.repo,  
              pull_number: context.payload.number,  
              state: "closed"  
            })  
