name: Run Scraper
on:
  workflow_dispatch:
  repository_dispatch:  # Allows triggering via API call

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: |
          python main.py > docs/price.txt
          echo "<meta http-equiv='refresh' content='0; url=https://agoncziDemos.github.io/YourRepoName/price.txt'>" > docs/index.html
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Update price" || echo "No changes"
          git push
