name: Update Price
on:
  workflow_dispatch:  # Manual trigger only
  schedule:
    - cron: '*/30 * * * *'  # Auto-run every 30 minutes

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run scraper
        run: |
          python main.py > docs/price.txt
          echo '<meta http-equiv="refresh" content="0; url=price.txt">' > docs/index.html
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Update price" || exit 0
          git push
