name: Run Scraper
on: 
  workflow_dispatch:
    inputs:
      confirm:
        description: "Run the scraper?"  
        required: true
        default: "yes"

permissions: read-all

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'yes'
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        run: python main.py
