name: Run Scraper
on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 12PM UTC
  workflow_dispatch:       # Manual trigger

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        run: python main.py
