mkdir -p .github/workflows
echo 'name: Run Scraper
on:
  schedule:
    - cron: "0 12 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python main.py' > .github/workflows/run.yml
